cd javaclasses
javac Frac.java
javac Duration.java
javac Pitch.java
javac Rational.java
javac Rhythm.java
javac Track.java
javac Pitch_Duration_Tuple.java
javac Composition.java
javac Chord.java
cd ..